# Generated by Django 5.0.2 on 2024-02-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthchceck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('pastdisease', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
            ],
        ),
    ]
